server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: web_manage
  registry:
    address: zookeeper://192.168.72.131:2181
  protocol:
    port: -1
  consumer:
    check: false
    timeout: 30000

